project:
  type: book # website
  output-dir: "_build"
  preview:
    port: 4567
    browser: true

# https://quarto.org/docs/books/
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Science Unleashed: Embracing Open Practices"
  author: "David Lippert"
  date: "last-modified" # "9/6/2024"
  date-format: "iso"
  #doi: "...."
  #isbn: "..."
  #issn: "..."
  #edition: "v2"

#website:

  site-url: https://david-lippert.github.io/science-unleashed-workshop
  repo-url: https://github.com/david-lippert/science-unleashed-workshop
  repo-branch: main
  repo-subdir: docs
  repo-actions: [edit, issue, source]
  #downloads: [pdf, epub, docx]

  # https://quarto.org/docs/websites/website-tools.html#google-analytics
  #google-analytics: "G-..."

  #sharing: [twitter, facebook]
  # https://quarto.org/docs/websites/website-tools.html#open-graph
  open-graph: true

  # https://quarto.org/docs/reference/projects/books.html#search
  search: true
    #location: sidebar # navbar, sidebar
    #type: textbox # overlay, textbox

  #cover-image: images/cover.png
  #favicon: images/favicon.ico

  # https://quarto.org/docs/websites/website-navigation.html#side-navigation
  #sidebar:
  #  logo: images/ospo-logo.png

  #sidebar:
  #  contents:
  #    - index.qmd
  #
  #    - section:
  #      href: prereqs/local-dev-setup/index.qmd
  #      title: "Prerequisites"
  #      contents:
  #        - prereqs/local-dev-setup/github.qmd
  #        - prereqs/local-dev-setup/vs-code-text-editor.qmd
  #        - prereqs/local-dev-setup/terminal.qmd
  #        - prereqs/local-dev-setup/anaconda.qmd
  #        - prereqs/local-dev-setup/git-client.qmd


  chapters:
    - index.qmd

    - "-------------"

    - part: "What is open science?""
      href: lessons/what-is-open-science/index.qmd
      chapters:
        - lessons/what-is-open-science/open-modules.ipynb


    - "-------------"

    - part: "Why open science?""
      href: lessons/why-open-science/index.qmd


    - "-------------"

    - part: "How to practice open science?""
      href: lessons/how-to-practice-open-science/index.qmd
      chapters:
        - lessons/how-to-practice-open-science/gw-resources.qmd
        - lessons/how-to-practice-open-science/open-modules.ipynb

    - "-------------"


  #appendices:


  # shows up at bottom of page
  #body-footer: "&copy; Copyright 2024, Your Name Here"

  #page-footer:
  #  center: |
  #    <p>&copy; Copyright 2024, GWU Open Source Program Office (OSPO)</p>


#bibliography: references.bib

format:
  html:
    # https://quarto.org/docs/output-formats/html-themes.html
    theme:
      light: default #flatly
      dark: darkly
    css: styles.css
    number-sections: false
    from: markdown+emoji # enable emojis


  #pdf:
  #  documentclass: scrreprt
